### ISSUE TITLE
Parsing of untyped syntax

### ISSUE THREAD

**Issue by effectfully** [effectfully/tiny-lang#20]
Currently we parse typed syntax directly. The advantages of parsing untyped syntax are

- quite easier to make parsing fast
- type errors are not parse errors. Currently an ill-typed expression will just refuse to parse. Seeing a type error instead of a parse would be much nicer
- `megaparsec`'s builtin machinery for parsing expressions will work better for us (currently it works in like half the cases)

**Comment by jakzale** [comment]
Closed by #48 .
