### ISSUE TITLE
Add proper declarations

### ISSUE THREAD

**Issue by effectfully** [effectfully/tiny-lang#33]
Now that we plan to add arrays and functions, distinguishing between variables of different types by means of weird syntactic tricks is no longer an option, we need proper type signatures.

**Comment by jakzale** [comment]
@effectfully, #13 mention external variables.

Are declarations four bound variables, or do we declare free/external variables as well?

**Comment by effectfully** [comment]
Declarations are only for free/external variables. For a bound/internal variable we can annotate its rhs with a type at the definition site (or not do that if the type is unambiguous, which is currently probably always the case).

So we need declarations precisely because those external variables are not bound anywhere and we have to specify their types somehow. And it also helps readability to declare all external variables upfront.

**Comment by jakzale** [comment]
Right, because we do not have functions, and we cannot properly specify an interface or an entry point to the program.  I think that once we add functions then we get rid of declarations by specifying which function is an entry point of the program, and then specifying that functions arguments.

Circling back to #51, do we want to
- go the direction of imperative languages and have declarations as a statement, or
- go the direction of functional languages and have declarations as lexical scoping bindings (without RHS)?

**Comment by effectfully** [comment]
> Right, because we do not have functions, and we cannot properly specify an interface or an entry point to the program. I think that once we add functions then we get rid of declarations by specifying which function is an entry point of the program, and then specifying that functions arguments.

That's an interesting perspective, I haven't thought of it. We can have the same convention as in Haskell: `main` is the entry point.

That means that we'll have to distinguish between functions and procedures, though. Just like we distinguish between expressions and statements right now (which is something that we have to do, because assertions can only be compiled when they're at the top level, see [this comment](https://github.com/effectfully/tiny-lang/issues/13#issuecomment-519057754), so "statements" arise naturally).

I.e. you can call a function (that can't contain any statements) only from an expression and a procedure (which is a bunch of statements) call is a treated as a statement. In that sense a `for` loop is a procedure.

I now think we should start with #51 first, otherwise it's too hard to change the language so that the changes make sense right now and after we fix #51.

What do you think?

**Comment by jakzale** [comment]
Ok, I will focus on #51 first.

**Comment by jakzale** [comment]
Fixed by #79
