### ISSUE TITLE
Drop the boolean language

### ISSUE THREAD

**Issue by effectfully** [effectfully/tiny-lang#40]
Now that this repo is not for toying around anymore, we should drop redundant stuff. I think, extracting the boolean language in its own repo (for didactic purposes) would be an improvement.

**Comment by effectfully** [comment]
Although we should preserve the boolean tests as they get embedded into the field tests.

**Comment by kwxm** [comment]
Thums up for that.  It was a bit annoying having these extra layers of directories because of the boolean/field versions.

**Comment by effectfully** [comment]
> Although we should preserve the boolean tests as they get embedded into the field tests.

Err, nevermind, I confused the repos, there are no relevant tests in this repo.

@kwxm 

> Thums up for that. It was a bit annoying having these extra layers of directories because of the boolean/field versions.

I do not find this annoying at all, actually. For me it's maintaining the dead code is annoying.

**Comment by effectfully** [comment]
Done.
