### ISSUE TITLE
Fix Statement vs Expr

### ISSUE THREAD

**Issue by jakzale** [effectfully/tiny-lang#51]
In most imperative programming languages _statements_ are the top level forms, with _expressions_ occurring inside _statements_.  At the moment, the language is _inside-out_, by having _statements_ inside expressions.

We can solve that in two possible ways:
- make the _statements_ toplevel, with _expressions_ occuring inside them, or
- forego _statements_ altogether by introducing `unit` type and treating `;` as expression sequencing operator (#44).

**Comment by effectfully** [comment]
> forego statements altogether by introducing unit type and treating ; as expression sequencing operator

Quoting [another comment](https://github.com/effectfully/tiny-lang/issues/33#issuecomment-606650606) (that I just left):

> we distinguish between expressions and statements right now (which is something that we have to do, because assertions can only be compiled when they're at the top level, see [this comment](https://github.com/effectfully/tiny-lang/issues/13#issuecomment-519057754), so "statements" arise naturally).

I did think about this option of having `unit` and `;` as a sequencing operator, but compiling that is hard and inefficient and it's not clear if this level of generality gives us anything substantial.

We could allow uncompilable syntax trees, but I'd rather clearly express the intentions in the structure of the AST, when possible.
