### ISSUE TITLE
Proper Type Environments, Binders, and Assignments

### ISSUE THREAD

**Issue by jakzale** [effectfully/tiny-lang#76]
Adding this as a single issue, because it addresses the following bug:

Because the statement in the inner loop should have been an assignment, but instead it is a shadowing declaration, therefore renamer uncouples them.  Furthermore, as we do not have proper binding rules for the for loop, type checker happily accepts this program, however the loop never gets evaluated, therefore the variable is never bound!

```
*** Failed! (after 646 tests and 23 shrinks):
        ERROR
          evaluation of the renamed program did not match the evaluation of the original program

        INITIAL STATE
          Env {unEnv = fromList [(26,Some 0)]}

        ORIGINAL PROGRAM
          for z_24 = 0 to -1 do
          let x_26 = x_26;
          end;
          let y_29 = if (0 == x_26) then 0 else 0;

        ORIGINAL PROGRAM FINAL STATE
          "[Some 0]"

        RENAMED PROGRAM
          for z_27 = 0 to -1 do
          let x_28 = x_26;
          end;
          let y_29 = if (0 == x_28) then 0 else 0;

        RENAMED PROGRAM FINAL STATE
          "VariableNotInScopeEvalError"
```

**Comment by effectfully** [comment]
Do we have a test where this program:

```
for z = 0 to -1 do
    let x = x;
end;
let y = if (0 == x) then 0 else 0;
```

gets compiled to the typed language, renamed and serialized to a golden file? If not, could you add it? Preferably before merging #78 in.

**Comment by jakzale** [comment]
Added in 21fe693
